In [235]:
import scipy
import numpy as np
import pandas as pd

In [236]:
X = np.array([[1.03, 1.03, 1.03, 1.03], [3, 4, 2, 5], [2, 1, 4, 2]])

p = np.array([1.0194, 3.4045, 2.4917])

#### Question 1.1

The risk free rate r is:

In [237]:
r = X[0, 0] - p[0]
r = round(r, 4)
r

0.0106

#### Queston 1.4

In [238]:
soln = np.linalg.lstsq(X, p)
soln

C:\Users\yrevtsov\AppData\Local\Temp\ipykernel_25700\3935164208.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  soln = np.linalg.lstsq(X, p)


(array([0.19514422, 0.15413259, 0.33320756, 0.30722438]),
 array([], dtype=float64),
 3,
 array([8.67020663, 2.82663493, 0.28504733]))

In [239]:
pi = soln[0]
pi

array([0.19514422, 0.15413259, 0.33320756, 0.30722438])

In [240]:
m = scipy.linalg.null_space(X).flatten()

m = m / np.abs(m).min()

In [241]:
m

array([-5.,  4.,  2., -1.])

In [242]:
res = (pi / (m*-1))
res

array([ 0.03902884, -0.03853315, -0.16660378,  0.30722438])

In [243]:
a_min = res[1]
a_max = res[0]

In [244]:
a_min

-0.0385331468974251

In [245]:
a_max

0.03902884339383697

#### 1.7

In [246]:
K = 4.5

In [247]:
c = np.maximum(X[1, :] - K, 0)
c

array([0. , 0. , 0. , 0.5])

In [248]:
ask = c @ (pi + m*a_min)
ask

0.1728787621359219

In [249]:
(pi + m*a_max)

array([0.        , 0.31024796, 0.41126524, 0.26819553])

In [250]:
c @ (pi + m*0)

0.15361218868720936

In [251]:
bid = c @ (pi + m*a_max)
bid

0.13409776699029086

In [252]:
(ask-bid)/np.average([bid, ask])

0.25266423629206075

In [253]:
pi + m * a

array([0.09514422, 0.23413259, 0.37320756, 0.28722438])

In [254]:
X @ m

array([-1.55431223e-15,  0.00000000e+00,  8.88178420e-16])

In [255]:
pi.round(4)

array([0.1951, 0.1541, 0.3332, 0.3072])

In [256]:
m

array([-5.,  4.,  2., -1.])

In [257]:
X @ (pi+m*0.22)

array([1.0194, 3.4045, 2.4917])

### Test

### Misc

payoff of portfolio at t1 for different states based on a set of weights

In [258]:
theta = np.array([1.77, -0.28, -0.26])

In [259]:
theta.T @ X

array([ 0.4631,  0.4431,  0.2231, -0.0969])

value/price of portfolio at t0

In [260]:
theta.T @ p

0.20323600000000008

In [261]:
theta.T @ X @ pi

0.20323600000000075

In [263]:
# 
theta.T @ (X - (np.array([p]).T*(1+r)))

array([ 0.2577097,  0.2377097,  0.0177097, -0.3022903])

In [264]:
theta.T @ X

array([ 0.4631,  0.4431,  0.2231, -0.0969])

In [265]:
theta

array([ 1.77, -0.28, -0.26])

In [266]:
theta * (np.array([p]).T*(1+r))

array([[ 1.82346398, -0.28845758, -0.26785347],
       [ 6.08984023, -0.96336456, -0.8945528 ],
       [ 4.45705828, -0.70507137, -0.65470913]])

In [267]:
theta.shape

(3,)

In [268]:
np.array([p]).T * np.ones([1, 4])

array([[1.0194, 1.0194, 1.0194, 1.0194],
       [3.4045, 3.4045, 3.4045, 3.4045],
       [2.4917, 2.4917, 2.4917, 2.4917]])

In [269]:
theta @ X

array([ 0.4631,  0.4431,  0.2231, -0.0969])

In [270]:
theta @ (np.array([p]).T * np.ones([1, 4]))

array([0.203236, 0.203236, 0.203236, 0.203236])

In [271]:
((theta @ X) - (theta.T @ (np.array([p*(1+r)]).T * np.ones([1, 4])))) * pi

array([ 0.05029056,  0.03663881,  0.00590101, -0.09287095])

In [272]:
X @ pi

array([1.0194, 3.4045, 2.4917])

In [274]:
theta

array([ 1.77, -0.28, -0.26])

In [276]:
(theta @ X) - (theta @ p*(1+r)) 

array([ 0.2577097,  0.2377097,  0.0177097, -0.3022903])

In [277]:
theta.T @ X @ pi

0.20323600000000075

In [278]:
theta @ p

0.20323600000000008

In [279]:
np.sum((pi+m*0) * (1+r))

1.0001996504854374

In [280]:
np.sum(pi)

0.9897087378640781

In [ ]:
1/(1+r)